import sys
import logging
from app.services.vector_db import VectorDBService

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def test_vector_db_service():
    print("==================================================")
    print("         Testing Vector Database Service          ")
    print("==================================================")
    
    try:
        # Initialize Vector DB Service (this connects to Qdrant and ensures collection exists)
        service = VectorDBService(collection_name="test_enterprise_rag")
        
        # Test document chunks
        test_chunks = [
            "The company's total revenue for the Q3 financial quarter of 2025 was 45 million dollars.",
            "Our primary machine learning framework is PyTorch, which we use to run local sentence embedding models.",
            "FastAPI is used to build high-performance web applications using python asynchronous tasks.",
            "The QA verification assistant audits responses generated by the agent system to prevent hallucinations.",
            "Enterprise data search requires a hybrid approach combining semantic models and keyword match statistics."
        ]
        
        test_metadata = [
            {"doc_name": "q3_financial_report.pdf", "page_number": 12},
            {"doc_name": "ml_infrastructure_guidelines.pdf", "page_number": 3},
            {"doc_name": "backend_api_architecture.pdf", "page_number": 1},
            {"doc_name": "agent_system_design.pdf", "page_number": 8},
            {"doc_name": "enterprise_search_strategies.pdf", "page_number": 4}
        ]
        
        # Ingest mock documents
        print("\n[TEST] Ingesting documents into Qdrant...")
        success = service.upsert_documents(test_chunks, test_metadata)
        assert success, "Failed to ingest documents"
        print("[OK] Document ingestion succeeded.")
        
        # Test Semantic Search
        query = "How much money did we make in Q3 2025?"
        print(f"\n[TEST] Querying Semantic Search for: '{query}'")
        semantic_results = service.search_semantic(query, limit=2)
        
        print(f"[OK] Semantic Search retrieved {len(semantic_results)} results:")
        for idx, hit in enumerate(semantic_results, start=1):
            print(f"     Rank {idx}: Score: {hit['score']:.4f} | File: {hit['metadata']['doc_name']} | Content: {hit['content']}")
            
        # Assert semantic retrieval matches the financial chunk
        assert "revenue" in semantic_results[0]["content"], "First semantic match did not fetch financial details"
        
        # Test Hybrid Search
        hybrid_query = "FastAPI backend python architecture"
        print(f"\n[TEST] Querying Hybrid Search (RRF) for: '{hybrid_query}'")
        hybrid_results = service.search_hybrid(hybrid_query, limit=2)
        
        print(f"[OK] Hybrid Search retrieved {len(hybrid_results)} results:")
        for idx, hit in enumerate(hybrid_results, start=1):
            print(f"     Rank {idx}: RRF Score: {hit['score']:.4f} | File: {hit['metadata']['doc_name']} | Content: {hit['content']}")
            
        assert len(hybrid_results) > 0, "Hybrid Search returned empty results"
        print("\n[SUCCESS] Vector Database & Hybrid Search are fully operational!")
        sys.exit(0)
        
    except Exception as e:
        print(f"\n[FAILED] Vector DB test failed. Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    test_vector_db_service()
