from fastapi import APIRouter, HTTPException, status
from app.schemas.chat import QueryRequest, ChatResponse, ChatTraceItem
from app.services.vector_db import VectorDBService
from app.core.config import settings
from app.agents.graph import app_graph
from langchain_core.messages import HumanMessage
import logging

logger = logging.getLogger(__name__)

router = APIRouter()
vector_db_service = VectorDBService(collection_name=settings.COLLECTION_NAME)

@router.post("/retrieve", status_code=status.HTTP_200_OK)
async def retrieve_contexts(payload: QueryRequest):
    """
    Retrieves the most semantically relevant text chunks for a query
    using Reciprocal Rank Fusion (RRF) hybrid search.
    """
    try:
        # Run hybrid retrieval
        results = vector_db_service.search_hybrid(
            query=payload.query,
            limit=payload.limit
        )
        return {
            "query": payload.query,
            "results": results
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Retrieval process failed: {e}"
        )

@router.post("/ask", response_model=ChatResponse, status_code=status.HTTP_200_OK)
async def ask_agents(payload: QueryRequest):
    """
    Queries the multi-agent RAG workflow. Runs the LangGraph network, collects execution
    traces, runs faithfulness checks, and returns the final verified answer.
    """
    try:
        # Define initial state
        graph_state = {
            "messages": [HumanMessage(content=payload.query)],
            "query": payload.query,
            "retrieved_contexts": [],
            "draft_response": "",
            "route": "",
            "verification_score": 0.0,
            "verification_reasoning": "",
            "verification_attempts": 0
        }
        
        # Stream events from LangGraph to capture intermediate traces
        events = app_graph.stream(graph_state)
        
        trace = []
        
        for event in events:
            for node_name, node_update in event.items():
                # Merge node updates into graph_state
                for key, val in node_update.items():
                    if key == "retrieved_contexts":
                        graph_state["retrieved_contexts"].extend(val)
                    elif key == "messages":
                        graph_state["messages"].extend(val)
                    else:
                        graph_state[key] = val
                
                details = ""
                # Build helpful trace details based on node execution
                if node_name == "router":
                    details = f"Decided routing path: '{graph_state.get('route')}'"
                elif node_name == "retrieve":
                    details = f"Retrieved {len(node_update.get('retrieved_contexts', []))} document chunks from Qdrant vector store."
                elif node_name == "research":
                    details = f"Retrieved {len(node_update.get('retrieved_contexts', []))} search results from Tavily Web Search."
                elif node_name == "generate":
                    details = "Draft response generated by Gemini model."
                elif node_name == "verify":
                    details = f"Faithfulness verification score: {node_update.get('verification_score', 1.0)} | Reasoning: {node_update.get('verification_reasoning', '')}"
                
                trace.append(ChatTraceItem(node=node_name, details=details))
                
        logger.info(f"Final compiled graph state: {graph_state}")
        return ChatResponse(
            answer=graph_state.get("draft_response", ""),
            trace=trace,
            sources=graph_state.get("retrieved_contexts", []),
            verification_score=graph_state.get("verification_score", 1.0),
            verification_reasoning=graph_state.get("verification_reasoning", "")
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent workflow execution failed: {e}"
        )
